name: test
on:
  - pull_request
jobs:
  xenial:
    container:
      image: vapor/swift:5.1-xenial
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - run: swift test --enable-test-discovery
  bionic:
    container:
      image: vapor/swift:5.1-bionic
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - run: swift test --enable-test-discovery
  thread:
    container:
      image: vapor/swift:5.1-bionic
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - run: swift test --enable-test-discovery --sanitize=thread
