name: test
on:
  - pull_request
jobs:
  linux:
    runs-on: ubuntu-latest
    strategy:
      matrix: 
        image: 
          - swift:5.2-xenial
          - swift:5.2-bionic
          - swift:5.3-xenial
          - swift:5.3-bionic
    container: ${{ matrix.image }}
    steps:
      - uses: actions/checkout@v2
      - run: swift test --enable-test-discovery --sanitize=thread
